# These are supported funding model platforms
# Uncomment and add your usernames/links to enable sponsorship

# github: [user1, user2]
# patreon: username
# open_collective: project-name
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# custom: ['https://example.com']
